# internsavy task 4
by snehal gupta

# first step-load the data and libraries

In [22]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [ ]:
# df=pd.read_csv("C:\\Users\\sneha\\Documents\\\internsavy\\Batsman_Data.csv")

In [5]:
df.head(50)

,Unnamed: 0,Bat1,Runs,BF,SR,4s,6s,Opposition,Ground,Start Date,Match_ID,Batsman,Player_ID
0,1,DNB,-,-,-,-,-,v India,Nagpur,18 Dec 2009,ODI # 2933,Oshane Thomas,49619
1,2,DNB,-,-,-,-,-,v India,Kolkata,24 Dec 2009,ODI # 2935,Oshane Thomas,49619
2,3,DNB,-,-,-,-,-,v India,Delhi,27 Dec 2009,ODI # 2936,Oshane Thomas,49619
3,4,DNB,-,-,-,-,-,v Bangladesh,Dhaka,4 Jan 2010,ODI # 2937,Oshane Thomas,49619
4,5,DNB,-,-,-,-,-,v India,Dhaka,5 Jan 2010,ODI # 2938,Oshane Thomas,49619
5,6,0*,0,8,0.00,0,0,v India,Dhaka,10 Jan 2010,ODI # 2941,Oshane Thomas,49619
6,7,0*,0,0,-,0,0,v England,The Oval,28 Jun 2011,ODI # 3165,Oshane Thomas,49619
7,8,DNB,-,-,-,-,-,v England,Leeds,1 Jul 2011,ODI # 3167,Oshane Thomas,49619
8,9,DNB,-,-,-,-,-,v England,Lord's,3 Jul 2011,ODI # 3168,Oshane Thomas,49619
9,10,1*,1,3,33.33,0,0,v England,Nottingham,6 Jul 2011,ODI # 3169,Oshane Thomas,49619
10,11,0*,0,2,0.00,0,0,v Australia,Pallekele,10 Aug 2011,ODI # 3175,Oshane Thomas,49619
11,12,0,0,2,0.00,0,0,v Pakistan,Dubai (DSC),11 Nov 2011,ODI # 3212,Oshane Thomas,49619
12,13,0*,0,0,-,0,0,v India,Dhaka,13 Mar 2012,ODI # 3259,Oshane Thomas,49619
13,14,0,0,4,0.00,0,0,v Pakistan,Dhaka,15 Mar 2012,ODI # 3260,Oshane Thomas,49619
14,15,0,0,1,0.00,0,0,v Bangladesh,Dhaka,20 Mar 2012,ODI # 3265,Oshane Thomas,49619
15,16,1,1,5,20.00,0,0,v India,Port of Spain,11 Jul 2013,ODI # 3388,Oshane Thomas,49619
16,17,DNB,-,-,-,-,-,v South Africa,Colombo (RPS),31 Jul 2013,ODI # 3401,Oshane Thomas,49619
17,18,1*,1,1,100.00,0,0,v Pakistan,Sharjah,18 Dec 2013,ODI # 3445,Oshane Thomas,49619
18,19,2*,2,11,18.18,0,0,v Pakistan,Abu Dhabi,25 Dec 2013,ODI # 3448,Oshane Thomas,49619
19,20,DNB,-,-,-,-,-,v Pakistan,Abu Dhabi,27 Dec 2013,ODI # 3450,Oshane Thomas,49619
20,21,DNB,-,-,-,-,-,v Bangladesh,Dhaka,22 Feb 2014,ODI # 3471,Oshane Thomas,49619
21,22,DNB,-,-,-,-,-,v Pakistan,Fatullah,25 Feb 2014,ODI # 3473,Oshane Thomas,49619
22,23,DNB,-,-,-,-,-,v Afghanistan,Dhaka,3 Mar 2014,ODI # 3481,Oshane Thomas,49619
23,24,DNB,-,-,-,-,-,v Bangladesh,Dhaka,6 Mar 2014,ODI # 3485,Oshane Thomas,49619
24,25,DNB,-,-,-,-,-,v Pakistan,Dhaka,8 Mar 2014,ODI # 3486,Oshane Thomas,49619
25,26,DNB,-,-,-,-,-,v Ireland,Dublin,6 May 2014,ODI # 3490,Oshane Thomas,49619
26,27,4*,4,5,80.00,0,0,v England,The Oval,22 May 2014,ODI # 3492,Oshane Thomas,49619
27,28,DNB,-,-,-,-,-,v England,Pallekele,13 Dec 2014,ODI # 3567,Oshane Thomas,49619
28,29,DNB,-,-,-,-,-,v England,Colombo (RPS),16 Dec 2014,ODI # 3569,Oshane Thomas,49619
29,30,0,0,3,0.00,0,0,v New Zealand,Dunedin,23 Jan 2015,ODI # 3588,Oshane Thomas,49619
30,31,3,3,5,60.00,0,0,v New Zealand,Dunedin,25 Jan 2015,ODI # 3590,Oshane Thomas,49619
31,32,7*,7,17,41.17,0,0,v New Zealand,Christchurch,14 Feb 2015,ODI # 3599,Oshane Thomas,49619
32,33,DNB,-,-,-,-,-,v Afghanistan,Dunedin,22 Feb 2015,ODI # 3609,Oshane Thomas,49619
33,34,DNB,-,-,-,-,-,v Bangladesh,Melbourne,26 Feb 2015,ODI # 3615,Oshane Thomas,49619
34,35,DNB,-,-,-,-,-,v England,Wellington,1 Mar 2015,ODI # 3619,Oshane Thomas,49619
35,36,DNB,-,-,-,-,-,v Pakistan,Dambulla,11 Jul 2015,ODI # 3664,Oshane Thomas,49619
36,37,1*,1,3,33.33,0,0,v Pakistan,Colombo (RPS),22 Jul 2015,ODI # 3671,Oshane Thomas,49619
37,38,DNB,-,-,-,-,-,v Pakistan,Hambantota,26 Jul 2015,ODI # 3672,Oshane Thomas,49619
38,39,1*,1,4,25.00,0,0,v West Indies,Colombo (RPS),1 Nov 2015,ODI # 3701,Oshane Thomas,49619
39,40,DNB,-,-,-,-,-,v West Indies,Colombo (RPS),4 Nov 2015,ODI # 3702,Oshane Thomas,49619
40,41,DNB,-,-,-,-,-,v West Indies,Pallekele,7 Nov 2015,ODI # 3704,Oshane Thomas,49619
41,42,8,8,9,88.88,0,0,v New Zealand,Christchurch,26 Dec 2015,ODI # 3714,Oshane Thomas,49619
42,43,DNB,-,-,-,-,-,v Ireland,Dublin (Malahide),18 Jun 2016,ODI # 3749,Oshane Thomas,49619
43,44,7,7,8,87.50,0,0,v England,Nottingham,21 Jun 2016,ODI # 3751,Oshane Thomas,49619
44,45,DNB,-,-,-,-,-,v England,Birmingham,24 Jun 2016,ODI # 3753,Oshane Thomas,49619
45,46,3*,3,4,75.00,0,0,v England,Bristol,26 Jun 2016,ODI # 3755,Oshane Thomas,49619
46,47,DNB,-,-,-,-,-,v England,The Oval,29 Jun 2016,ODI # 3757,Oshane Thomas,49619
47,48,10,10,23,43.47,1,0,v England,Cardiff,2 Jul 2016,ODI # 3758,Oshane Thomas,49619
48,49,0,0,1,0.00,0,0,v Australia,Pallekele,4 Sep 2016,ODI # 3776,Oshane Thomas,49619
49,50,DNB,-,-,-,-,-,v Zimbabwe,Harare,14 Nov 2016,ODI # 3804,Oshane Thomas,49619

In [7]:
data = df.drop(columns=['Unnamed: 0'])

In [8]:
data['Start Date'] = pd.to_datetime(data['Start Date'])

In [9]:
data = data.dropna()

In [11]:
data.head(50)

,Bat1,Runs,BF,SR,4s,6s,Opposition,Ground,Start Date,Match_ID,Batsman,Player_ID
0,DNB,-,-,-,-,-,v India,Nagpur,2009-12-18,ODI # 2933,Oshane Thomas,49619
1,DNB,-,-,-,-,-,v India,Kolkata,2009-12-24,ODI # 2935,Oshane Thomas,49619
2,DNB,-,-,-,-,-,v India,Delhi,2009-12-27,ODI # 2936,Oshane Thomas,49619
3,DNB,-,-,-,-,-,v Bangladesh,Dhaka,2010-01-04,ODI # 2937,Oshane Thomas,49619
4,DNB,-,-,-,-,-,v India,Dhaka,2010-01-05,ODI # 2938,Oshane Thomas,49619
5,0*,0,8,0.00,0,0,v India,Dhaka,2010-01-10,ODI # 2941,Oshane Thomas,49619
6,0*,0,0,-,0,0,v England,The Oval,2011-06-28,ODI # 3165,Oshane Thomas,49619
7,DNB,-,-,-,-,-,v England,Leeds,2011-07-01,ODI # 3167,Oshane Thomas,49619
8,DNB,-,-,-,-,-,v England,Lord's,2011-07-03,ODI # 3168,Oshane Thomas,49619
9,1*,1,3,33.33,0,0,v England,Nottingham,2011-07-06,ODI # 3169,Oshane Thomas,49619
10,0*,0,2,0.00,0,0,v Australia,Pallekele,2011-08-10,ODI # 3175,Oshane Thomas,49619
11,0,0,2,0.00,0,0,v Pakistan,Dubai (DSC),2011-11-11,ODI # 3212,Oshane Thomas,49619
12,0*,0,0,-,0,0,v India,Dhaka,2012-03-13,ODI # 3259,Oshane Thomas,49619
13,0,0,4,0.00,0,0,v Pakistan,Dhaka,2012-03-15,ODI # 3260,Oshane Thomas,49619
14,0,0,1,0.00,0,0,v Bangladesh,Dhaka,2012-03-20,ODI # 3265,Oshane Thomas,49619
15,1,1,5,20.00,0,0,v India,Port of Spain,2013-07-11,ODI # 3388,Oshane Thomas,49619
16,DNB,-,-,-,-,-,v South Africa,Colombo (RPS),2013-07-31,ODI # 3401,Oshane Thomas,49619
17,1*,1,1,100.00,0,0,v Pakistan,Sharjah,2013-12-18,ODI # 3445,Oshane Thomas,49619
18,2*,2,11,18.18,0,0,v Pakistan,Abu Dhabi,2013-12-25,ODI # 3448,Oshane Thomas,49619
19,DNB,-,-,-,-,-,v Pakistan,Abu Dhabi,2013-12-27,ODI # 3450,Oshane Thomas,49619
20,DNB,-,-,-,-,-,v Bangladesh,Dhaka,2014-02-22,ODI # 3471,Oshane Thomas,49619
21,DNB,-,-,-,-,-,v Pakistan,Fatullah,2014-02-25,ODI # 3473,Oshane Thomas,49619
22,DNB,-,-,-,-,-,v Afghanistan,Dhaka,2014-03-03,ODI # 3481,Oshane Thomas,49619
23,DNB,-,-,-,-,-,v Bangladesh,Dhaka,2014-03-06,ODI # 3485,Oshane Thomas,49619
24,DNB,-,-,-,-,-,v Pakistan,Dhaka,2014-03-08,ODI # 3486,Oshane Thomas,49619
25,DNB,-,-,-,-,-,v Ireland,Dublin,2014-05-06,ODI # 3490,Oshane Thomas,49619
26,4*,4,5,80.00,0,0,v England,The Oval,2014-05-22,ODI # 3492,Oshane Thomas,49619
27,DNB,-,-,-,-,-,v England,Pallekele,2014-12-13,ODI # 3567,Oshane Thomas,49619
28,DNB,-,-,-,-,-,v England,Colombo (RPS),2014-12-16,ODI # 3569,Oshane Thomas,49619
29,0,0,3,0.00,0,0,v New Zealand,Dunedin,2015-01-23,ODI # 3588,Oshane Thomas,49619
30,3,3,5,60.00,0,0,v New Zealand,Dunedin,2015-01-25,ODI # 3590,Oshane Thomas,49619
31,7*,7,17,41.17,0,0,v New Zealand,Christchurch,2015-02-14,ODI # 3599,Oshane Thomas,49619
32,DNB,-,-,-,-,-,v Afghanistan,Dunedin,2015-02-22,ODI # 3609,Oshane Thomas,49619
33,DNB,-,-,-,-,-,v Bangladesh,Melbourne,2015-02-26,ODI # 3615,Oshane Thomas,49619
34,DNB,-,-,-,-,-,v England,Wellington,2015-03-01,ODI # 3619,Oshane Thomas,49619
35,DNB,-,-,-,-,-,v Pakistan,Dambulla,2015-07-11,ODI # 3664,Oshane Thomas,49619
36,1*,1,3,33.33,0,0,v Pakistan,Colombo (RPS),2015-07-22,ODI # 3671,Oshane Thomas,49619
37,DNB,-,-,-,-,-,v Pakistan,Hambantota,2015-07-26,ODI # 3672,Oshane Thomas,49619
38,1*,1,4,25.00,0,0,v West Indies,Colombo (RPS),2015-11-01,ODI # 3701,Oshane Thomas,49619
39,DNB,-,-,-,-,-,v West Indies,Colombo (RPS),2015-11-04,ODI # 3702,Oshane Thomas,49619
40,DNB,-,-,-,-,-,v West Indies,Pallekele,2015-11-07,ODI # 3704,Oshane Thomas,49619
41,8,8,9,88.88,0,0,v New Zealand,Christchurch,2015-12-26,ODI # 3714,Oshane Thomas,49619
42,DNB,-,-,-,-,-,v Ireland,Dublin (Malahide),2016-06-18,ODI # 3749,Oshane Thomas,49619
43,7,7,8,87.50,0,0,v England,Nottingham,2016-06-21,ODI # 3751,Oshane Thomas,49619
44,DNB,-,-,-,-,-,v England,Birmingham,2016-06-24,ODI # 3753,Oshane Thomas,49619
45,3*,3,4,75.00,0,0,v England,Bristol,2016-06-26,ODI # 3755,Oshane Thomas,49619
46,DNB,-,-,-,-,-,v England,The Oval,2016-06-29,ODI # 3757,Oshane Thomas,49619
47,10,10,23,43.47,1,0,v England,Cardiff,2016-07-02,ODI # 3758,Oshane Thomas,49619
48,0,0,1,0.00,0,0,v Australia,Pallekele,2016-09-04,ODI # 3776,Oshane Thomas,49619
49,DNB,-,-,-,-,-,v Zimbabwe,Harare,2016-11-14,ODI # 3804,Oshane Thomas,49619

# preprocess the data

In [12]:
# Step 2: Remove unnecessary columns
columns_to_drop = ['Runs', 'SR', 'Opposition', 'Ground', 'Start Date', 'Match_ID', 'Batsman', 'Player_ID']
data = data.drop(columns_to_drop, axis=1)

In [13]:
data

       Bat1  BF 4s 6s
0       DNB   -  -  -
1       DNB   -  -  -
2       DNB   -  -  -
3       DNB   -  -  -
4       DNB   -  -  -
...     ...  .. .. ..
11144    46  61  6  1
11145     3   6  0  0
11146     1   8  0  0
11147   DNB   -  -  -
11148  TDNB   -  -  -

[11149 rows x 4 columns]

In [14]:
# Replace '-' and 'DNB' with appropriate values (e.g., 0)
data.replace('-', 0, inplace=True)
data.replace('DNB', 0, inplace=True)

In [15]:
data

       Bat1  BF 4s 6s
0         0   0  0  0
1         0   0  0  0
2         0   0  0  0
3         0   0  0  0
4         0   0  0  0
...     ...  .. .. ..
11144    46  61  6  1
11145     3   6  0  0
11146     1   8  0  0
11147     0   0  0  0
11148  TDNB   0  0  0

[11149 rows x 4 columns]

In [16]:
# Convert 'Bat1' column to numeric
data['Bat1'] = pd.to_numeric(data['Bat1'], errors='coerce')

In [17]:
# Drop rows with missing values
data.dropna(inplace=True)

In [20]:
label_encoder = LabelEncoder()
data['Bat1'] = label_encoder.fit_transform(data['Bat1'])

In [35]:
data.head(50)

    Bat1  BF 4s 6s
0      0   0  0  0
1      0   0  0  0
2      0   0  0  0
3      0   0  0  0
4      0   0  0  0
7      0   0  0  0
8      0   0  0  0
11     0   2  0  0
13     0   4  0  0
14     0   1  0  0
15     1   5  0  0
16     0   0  0  0
19     0   0  0  0
20     0   0  0  0
21     0   0  0  0
22     0   0  0  0
23     0   0  0  0
24     0   0  0  0
25     0   0  0  0
27     0   0  0  0
28     0   0  0  0
29     0   3  0  0
30     3   5  0  0
32     0   0  0  0
33     0   0  0  0
34     0   0  0  0
35     0   0  0  0
37     0   0  0  0
39     0   0  0  0
40     0   0  0  0
41     8   9  0  0
42     0   0  0  0
43     7   8  0  0
44     0   0  0  0
46     0   0  0  0
47    10  23  1  0
48     0   1  0  0
49     0   0  0  0
50     0   1  0  0
52     0   0  0  0
53     0   0  0  0
54     3  12  0  0
56     0   6  0  0
58     8   9  1  0
59     0   1  0  0
61     0   3  0  0
62     0   0  0  0
63    26  34  3  0
65     1   2  0  0
67     0   0  0  0

In [36]:
# Split the data into input features (X) and target variable (y)
X = data[['BF', '4s', '6s']]
y = data['Bat1']

In [37]:
# Step 2: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [38]:
# Step 3: Build and train the model
model = RandomForestRegressor()
model.fit(X_train, y_train)

RandomForestRegressor()

In [43]:
# Step 4: Make predictions
new_data = pd.DataFrame({
    'BF': [2, 0, 0, 0],
    '4s': [0, 0, 7, 2],
    '6s': [9, 0, 0, 0]
})

In [44]:
prediction = model.predict(new_data)
print('Predicted Bat1:', prediction)

Predicted Bat1: [10.98046005  0.         26.46566667  8.01      ]